BanTV/Models/KhachHang.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace BanTV.Models
{
    public partial class KhachHang
    {
        public KhachHang()
        {
            DiaChi = new HashSet<DiaChi>();
            HoaDon = new HashSet<HoaDon>();
        }

        [Key]
        [Column("makh")]
        public int Makh { get; set; }

       
        [Required(ErrorMessage = "Vui lòng nhập tên.")]
        [RegularExpression(@"^[^\d]+$", ErrorMessage = "Tên không được chứa chữ số.")]
        [Column("ten")]
        [StringLength(100)]
        public string Ten { get; set; }


        [Required(ErrorMessage = "Vui lòng nhập số điện thoại.")]
        [RegularExpression(@"^0[0-9]{9}$", ErrorMessage = "Số điện thoại phải bắt đầu bằng số 0 và có đúng 10 chữ số.")]
        [Column("dienthoai")]
        [StringLength(20)]
        public string Dienthoai { get; set; }


        [Required(ErrorMessage = "Vui lòng Email.")]
        [EmailAddress(ErrorMessage = "Địa chỉ email không hợp lệ.")]
        [Column("email")]
        [StringLength(255)]
        public string Email { get; set; }




        [Column("matkhau")]
        [StringLength(255)]
        public string Matkhau { get; set; }
        [Column("daxoa")]
        public int? Daxoa { get; set; }

        [InverseProperty("MakhNavigation")]
        public virtual ICollection<DiaChi> DiaChi { get; set; }
        [InverseProperty("MakhNavigation")]
        public virtual ICollection<HoaDon> HoaDon { get; set; }
    }
}

BanTV/Controllers/KhachHangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BanTV.Data;
using BanTV.Models;
using Microsoft.AspNetCore.Http;

namespace BanTV.Controllers
{
    public class KhachHangsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public KhachHangsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public void GetInfo()
        {
            string email = HttpContext.Session.GetString("nhanvien");
            ViewBag.nhanvien = _context.NhanVien.FirstOrDefault(n => n.Email == email);
        }


        // GET: KhachHangs
        public async Task<IActionResult> Index()

        {
            GetInfo();
            return View(await _context.KhachHang.OrderByDescending(H => H.Makh).ToListAsync());
        }

        // GET: KhachHangs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHang
                .FirstOrDefaultAsync(m => m.Makh == id);
            if (khachHang == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(khachHang);
        }

       
        // GET: KhachHangs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHang
                .FirstOrDefaultAsync(m => m.Makh == id);
            if (khachHang == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(khachHang);
        }

        // POST: KhachHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var khachHang = await _context.KhachHang.FindAsync(id);
            khachHang.Daxoa = 3;
            _context.KhachHang.Update(khachHang);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KhachHangExists(int id)
        {
            return _context.KhachHang.Any(e => e.Makh == id);
        }











        public async Task<IActionResult> Khoa(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHang
                .FirstOrDefaultAsync(m => m.Makh == id);
            if (khachHang == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(khachHang);
        }
        [HttpPost, ActionName("Khoa")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Khoamatkhau(int id)
        {
            var khachHang = await _context.KhachHang.FindAsync(id);
            khachHang.Daxoa = 1;
            _context.KhachHang.Update(khachHang);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }







        public async Task<IActionResult> Mo(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHang
                .FirstOrDefaultAsync(m => m.Makh == id);
            if (khachHang == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(khachHang);
        }
        [HttpPost, ActionName("Mo")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Momatkhau(int id)
        {
            var khachHang = await _context.KhachHang.FindAsync(id);
            khachHang.Daxoa = 0;
            _context.KhachHang.Update(khachHang);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Search(string SearchKey)
        {
            var lstHang = await _context.KhachHang.Include(m => m.DiaChi)
                            .Where(k => k.Ten.Contains(SearchKey) && k.Daxoa !=3).ToListAsync();
            GetInfo();
            return View(lstHang);
        }
    }
}

BanTV/Views/KhachHangs/Delete.cshtml
@model BanTV.Models.KhachHang

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KhachHang</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dienthoai)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dienthoai)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Matkhau)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Matkhau)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Daxoa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Daxoa)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Makh" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BanTV/Views/KhachHangs/Details.cshtml
@model BanTV.Models.KhachHang

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Details</h1>

<div>
    <h4>KhachHang</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dienthoai)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dienthoai)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Matkhau)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Matkhau)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Daxoa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Daxoa)
        </dd>
    </dl>
</div>
<div>
   
    <a asp-action="Index">Back to List</a>
</div>

BanTV/Views/KhachHangs/Index.cshtml
@model IEnumerable<BanTV.Models.KhachHang>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="  text-center ">Quản lý khách hàng</h1>
<br />
<div class="d-flex flex-row">
    <form asp-controller="KhachHangs" asp-action="Search">
        <input type="search" name="SearchKey" placeholder="Tìm kiếm...." class="form-control" />
    </form>

</div>
<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Ten)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dienthoai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                Đã đăng kí
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Daxoa)
            </th>
            <th>
                Khóa mật khẩu
            </th>


            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Ten)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dienthoai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                @if (item.Matkhau == null)
                {
                    <td>Chưa đăng ký</td>
                }
                else
                {
                    <td>Đã đăng ký</td>
                }

                @if (item.Daxoa == 3)
                {
                    <td>Đã xóa</td>
                }
                else
                {
                    <td></td>
                }

                @if (item.Daxoa == 0)
                {
                    <td class="text-center"><a class="btn btn-outline-success" asp-action="Khoa" asp-route-id="@item.Makh">khóa mật khẩu</a></td>

                }
                else
                @if (item.Daxoa == 1)
                {
                    <td class="text-center"><a class="btn btn-outline-success" asp-action="Mo" asp-route-id="@item.Makh">mở mật khẩu</a></td>

                }
                else
                {
                    <td></td>
                }

                <td>
                    <a asp-action="Details" asp-route-id="@item.Makh" class="btn btn-warning">Xem</a>
                    <a asp-action="Delete" asp-route-id="@item.Makh" class="btn btn-danger">Xóa</a>
                </td>
            </tr>
        }
    </tbody>
</table>

BanTV/Views/KhachHangs/Khoa.cshtml
@model BanTV.Models.KhachHang

@{
    ViewData["Title"] = "Khoa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Khóa mật khẩu</h1>

<div>
    <h4>KhachHang</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dienthoai)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dienthoai)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Matkhau)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Matkhau)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Daxoa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Daxoa)
        </dd>
    </dl>

    <form asp-action="Khoa">
        <input type="hidden" asp-for="Makh" />
        <input type="submit" value="Khóa mật khẩu" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BanTV/Views/KhachHangs/Mo.cshtml
@model BanTV.Models.KhachHang

@{
    ViewData["Title"] = "Mo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Khóa mật khẩu</h1>

<div>
    <h4>KhachHang</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dienthoai)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dienthoai)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Matkhau)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Matkhau)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Daxoa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Daxoa)
        </dd>
    </dl>

    <form asp-action="Mo">
        <input type="hidden" asp-for="Makh" />
        <input type="submit" value="Mở mật khẩu" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BanTV/Views/KhachHangs/Search.cshtml
@model IEnumerable<BanTV.Models.KhachHang>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>
<br />
<div class="d-flex flex-row">
    <form asp-controller="KhachHangs" asp-action="Search">
        <input type="search" name="SearchKey" placeholder="Tìm kiếm...." class="form-control" />
    </form>

</div>
<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Ten)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dienthoai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                Đã đăng kí
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Daxoa)
            </th>
            <th>
                Khóa mật khẩu
            </th>


            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Ten)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dienthoai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                @if (item.Matkhau == null)
                {
                    <td>Chưa đăng ký</td>
                }
                else
                {
                    <td>Đã đăng ký</td>
                }

                @if (item.Daxoa == 3)
                {
                    <td>Đã xóa</td>
                }
                else
                {
                    <td></td>
                }

                @if (item.Daxoa == 0)
                {
                    <td class="text-center"><a class="btn btn-outline-success" asp-action="Khoa" asp-route-id="@item.Makh">khóa mật khẩu</a></td>

                }
                else
                @if (item.Daxoa == 1)
                {
                    <td class="text-center"><a class="btn btn-outline-success" asp-action="Mo" asp-route-id="@item.Makh">mở mật khẩu</a></td>

                }
                else
                {
                    <td></td>
                }

                <td>
                    <a asp-action="Details" asp-route-id="@item.Makh" class="btn btn-warning">Xem</a>
                    <a asp-action="Delete" asp-route-id="@item.Makh" class="btn btn-danger">Xóa</a>
                </td>
            </tr>
        }
    </tbody>
</table>