BanTV/Controllers/DanhMucsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BanTV.Data;
using BanTV.Models;
using Microsoft.AspNetCore.Http;

namespace BanTV.Controllers
{
    public class DanhMucsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DanhMucsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public void GetInfo()
        {
            string email = HttpContext.Session.GetString("nhanvien");
            ViewBag.nhanvien = _context.NhanVien.FirstOrDefault(n => n.Email == email);
            ViewBag.mathang = _context.MatHang.ToList();

        }
        // GET: DanhMucs
        public async Task<IActionResult> Index()
        {
            GetInfo();
            return View(await _context.DanhMuc.ToListAsync());
        }

        // GET: DanhMucs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhMuc = await _context.DanhMuc
                .FirstOrDefaultAsync(m => m.Madm == id);
            if (danhMuc == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(danhMuc);
        }

        // GET: DanhMucs/Create
        public IActionResult Create()
        {
            GetInfo();
            return View();
        }

        // POST: DanhMucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Madm,Ten")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(danhMuc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            GetInfo();
            return View(danhMuc);
        }

        // GET: DanhMucs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhMuc = await _context.DanhMuc.FindAsync(id);
            if (danhMuc == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(danhMuc);
        }

        // POST: DanhMucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Madm,Ten")] DanhMuc danhMuc)
        {
            if (id != danhMuc.Madm)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(danhMuc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DanhMucExists(danhMuc.Madm))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            GetInfo();
            return View(danhMuc);
        }

        // GET: DanhMucs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var danhMuc = await _context.DanhMuc
                .FirstOrDefaultAsync(m => m.Madm == id);
            if (danhMuc == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(danhMuc);
        }

        // POST: DanhMucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var danhMuc = await _context.DanhMuc.FindAsync(id);
            _context.DanhMuc.Remove(danhMuc);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DanhMucExists(int id)
        {
            return _context.DanhMuc.Any(e => e.Madm == id);
        }
        public async Task<IActionResult> Search(string SearchKey)
        {
            var lstHang = await _context.DanhMuc.Include(m => m.MatHang)
                            .Where(k => k.Ten.Contains(SearchKey)).ToListAsync();
            GetInfo();
            return View(lstHang);
        }
    }
}

BanTV/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BanTV.Data;
using BanTV.Models;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using System.Data;
using ClosedXML.Excel;
using System.IO;

namespace BanTV.Controllers
{
    public class MainController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MainController(ApplicationDbContext context)
        {
            _context = context;
        }



        public IActionResult Index()
        {
            GetInfo();
            return View();
        }

        // Thống kê theo ngày
        public IActionResult ThongKeTheoNgay()
        {
            GetInfo();
            return View();
        }

        [HttpPost]
        public IActionResult XemThongKeTheoNgay(DateTime Ngaybatdau, DateTime Ngayketthuc)
        {
            var lstHD = _context.HoaDon.Include(m => m.MakhNavigation).Where(d => d.Ngay >= Ngaybatdau && d.Ngay <= Ngayketthuc && d.Trangthai == 3);
            int tongtien = 0;
            foreach (HoaDon hd in lstHD)
            {
                tongtien += hd.Tongtien;
            }
            ViewData["ngaybatdau"] = Ngaybatdau.Day.ToString() + "/" + Ngaybatdau.Month.ToString() + "/" + Ngaybatdau.Year.ToString();
            ViewData["ngayketthuc"] = Ngayketthuc.Day.ToString() + "/" + Ngayketthuc.Month.ToString() + "/" + Ngayketthuc.Year.ToString();
            ViewData["tongtien"] = tongtien.ToString("n0");
            GetInfo();
            return View(lstHD);
        }

        public IActionResult ThongKeMatHangTheoNgay()
        {
            GetInfo();
            return View();
        }
        public IActionResult XemThongKeMatHangTheoNgay(DateTime Ngaybatdau, DateTime Ngayketthuc)
        {
            var lstHD = _context.CthoaDon.Include(m => m.MamhNavigation).Include(n =>n.MahdNavigation).Where(d => d.MahdNavigation.Ngay >= Ngaybatdau && d.MahdNavigation.Ngay <= Ngayketthuc && d.MahdNavigation.Trangthai == 3);
         
            ViewData["ngaybatdau"] = Ngaybatdau.Day.ToString() + "/" + Ngaybatdau.Month.ToString() + "/" + Ngaybatdau.Year.ToString();
            ViewData["ngayketthuc"] = Ngayketthuc.Day.ToString() + "/" + Ngayketthuc.Month.ToString() + "/" + Ngayketthuc.Year.ToString();
         
            GetInfo();
            return View(lstHD);
        }
     
       

        public IActionResult ThongKeKhachHang()
        {
            GetInfo();
            return View();
        }

        public IActionResult XemThongKeKhachHang(string emailkhachhang)
        {
            var lstHoaDon = _context.HoaDon.Include(m => m.MakhNavigation)
                            .Where(h => h.MakhNavigation.Email == emailkhachhang && h.MakhNavigation.Matkhau != null && h.Trangthai == 3);
            int tongtien = 0;
            foreach (HoaDon hd in lstHoaDon)
            {
                tongtien += hd.Tongtien;
            }
            ViewBag.ttkhachhang = _context.KhachHang.FirstOrDefault(k => k.Email == emailkhachhang && k.Matkhau != null);
            ViewData["tongtien"] = tongtien.ToString("n0");
            GetInfo();
            return View(lstHoaDon);
        }


        public void GetInfo()
        {
            string email = HttpContext.Session.GetString("nhanvien");
            ViewBag.nhanvien = _context.NhanVien.FirstOrDefault(n => n.Email == email);
            ViewBag.mathang = _context.MatHang.ToList();
        }

        // Thống kê theo mặt hàng
        public IActionResult ThongKeTheoMatHang()
        {
            GetInfo();
            return View();
        }

        [HttpPost]
        public IActionResult XemThongKeTheoMatHang(int id)
        {
            var lstctHD = _context.CthoaDon.Include(m => m.MamhNavigation).Where(n=>n.MahdNavigation.Trangthai==3).Where(j => j.Mamh == id);
            int tongtien = 0;
            foreach (CthoaDon cthd in lstctHD)
            {
                tongtien += cthd.Thanhtien;
            }
            ViewData["tongtien"] = tongtien.ToString("n0");
            GetInfo();
            return View(lstctHD);
        }


        public async Task<IActionResult> Details(int id)
        {
            var hd = _context.CthoaDon.Include(k => k.MamhNavigation).Where(m => m.Mahd == id);
            GetInfo();
            return View(await hd.ToListAsync());
        }

        public IActionResult HoaDonChuaDuyet()
        {
            var lstHoaDon = _context.HoaDon
                            .Include(k => k.MakhNavigation)
                            .Include(d => d.MadcNavigation)
                            .Where(h => h.Trangthai == 0);

            GetInfo();
            return View(lstHoaDon);
        }

        public IActionResult HoaDonDaDuyet()
        {
            var lstHoaDon = _context.HoaDon
                            .Include(k => k.MakhNavigation)
                            .Include(d => d.MadcNavigation)
                            .Where(h => h.Trangthai == 1);

            GetInfo();
            return View(lstHoaDon);
        }

        public IActionResult HoaDonDaHuy()
        {
            var lstHoaDon = _context.HoaDon
                            .Include(k => k.MakhNavigation)
                            .Include(d => d.MadcNavigation)
                            .Where(h => h.Trangthai == 2);

            GetInfo();
            return View(lstHoaDon);
        }
   



        public IActionResult ChiTietHoaDonChuaDuyet(int id)
        {
            HoaDon hd = _context.HoaDon
                        .Include(k => k.MakhNavigation)
                        .Include(d => d.MadcNavigation)
                        .FirstOrDefault(h => h.Mahd == id);
            var lstCTHoaDon = _context.CthoaDon.Include(c => c.MamhNavigation).Where(h => h.Mahd == id);
            ViewBag.chittiethoadon = lstCTHoaDon;
            GetInfo();
            return View(hd);
        }

        public IActionResult ChiTietHoaDonDaDuyet(int id)
        {
            HoaDon hd = _context.HoaDon
                        .Include(k => k.MakhNavigation)
                        .Include(d => d.MadcNavigation)
                        .FirstOrDefault(h => h.Mahd == id);
            var lstCTHoaDon = _context.CthoaDon.Include(c => c.MamhNavigation).Where(h => h.Mahd == id);
            ViewBag.chittiethoadon = lstCTHoaDon;
            GetInfo();
            return View(hd);
        }

        public IActionResult ChiTietHoaDonDaHuy(int id)
        {
            HoaDon hd = _context.HoaDon
                        .Include(k => k.MakhNavigation)
                        .Include(d => d.MadcNavigation)
                        .FirstOrDefault(h => h.Mahd == id);
            var lstCTHoaDon = _context.CthoaDon.Include(c => c.MamhNavigation).Where(h => h.Mahd == id);
            ViewBag.chittiethoadon = lstCTHoaDon;
            GetInfo();
            return View(hd);
        }

        public async Task<IActionResult> DuyetDonHang(int id)
        {
            HoaDon hd = _context.HoaDon.FirstOrDefault(h => h.Mahd == id);
            hd.Trangthai = 1;
            _context.Update(hd);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(HoaDonChuaDuyet));
        }

        public async Task<IActionResult> HuyDonHang(int id)
        {
            HoaDon hd = _context.HoaDon.FirstOrDefault(h => h.Mahd == id);
            hd.Trangthai = 2;
            _context.Update(hd);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(HoaDonChuaDuyet));
        }
        public async Task<IActionResult> VanChuyen(int id)
        {
            HoaDon hd = _context.HoaDon.FirstOrDefault(h => h.Mahd == id);
            hd.Trangthai = 6;
            _context.Update(hd);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(HoaDonChuaDuyet));
        }

        public IActionResult HoaDonDagiao()
        {
            var lstHoaDon = _context.HoaDon
                            .Include(k => k.MakhNavigation)
                            .Include(d => d.MadcNavigation)
                            .Where(h => h.Trangthai == 3);

            GetInfo();
            return View(lstHoaDon);
        }
        public IActionResult ChiTietHoaDonGiao(int id)
        {
            HoaDon hd = _context.HoaDon
                        .Include(k => k.MakhNavigation)
                        .Include(d => d.MadcNavigation)
                        .FirstOrDefault(h => h.Mahd == id);
            var lstCTHoaDon = _context.CthoaDon.Include(c => c.MamhNavigation).Where(h => h.Mahd == id);
            ViewBag.chittiethoadon = lstCTHoaDon;
            GetInfo();
            return View(hd);
        }
    

        public IActionResult HangHoanTra()
        {
            var lstHoaDon = _context.HoaDon
                            .Include(k => k.MakhNavigation)
                            .Include(d => d.MadcNavigation)
                            .Where(h => h.Trangthai == 4);

            GetInfo();
            return View(lstHoaDon);
        }
        public IActionResult ChiTietHangHoanTra(int id)
        {
            HoaDon hd = _context.HoaDon
                        .Include(k => k.MakhNavigation)
                        .Include(d => d.MadcNavigation)
                        .FirstOrDefault(h => h.Mahd == id);
            var lstCTHoaDon = _context.CthoaDon.Include(c => c.MamhNavigation).Where(h => h.Mahd == id);
            ViewBag.chittiethoadon = lstCTHoaDon;
            GetInfo();
            return View(hd);
        }


        public IActionResult HoaDonCanGiao()
        {
            var lstHoaDon = _context.HoaDon
                            .Include(k => k.MakhNavigation)
                            .Include(d => d.MadcNavigation)

BanTV/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <link rel="shortcut icon" type="image/png" href="/../assets/images/logos/favicon.png" />
    <link rel="stylesheet" href="/../assets/css/styles.min.css" />
</head>

<body>
    <!--  Body Wrapper -->
    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed">

        <!-- Sidebar Start -->
        <aside class="left-sidebar">

            <!-- Sidebar scroll-->
            <div>
                </br>
                <div>
                  
                    <a class="navbar-brand d-flex align-items-center px-4 px-lg-5" asp-action="Index" asp-controller="Main">
                        <h2 class="m-0 text-primary"><i class="bi bi-shop-window"></i> Cửa hàng TV</h2>
                    </a>
                </div>

                <!-- Sidebar navigation-->
                <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
                    <ul id="sidebarnav">
                        @if (ViewBag.nhanvien.Quyen == 1)
                        {
                            <li class="nav-small-cap">
                                <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                                <span class="hide-menu">Trang quản lý </span>
                            </li>

                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-action="Index" asp-controller="DanhMucs">

                                    <span class="hide-menu">Quản lý danh mục</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-action="Index" asp-controller="MatHangs">

                                    <span class="hide-menu">Quản lý sản phẩm</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-action="Index" asp-controller="KhachHangs">

                                    <span class="hide-menu">Quản lý khách hàng</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-action="Index" asp-controller="NhanViens">

                                    <span class="hide-menu">Quản lý nhân viên</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-controller="Main" asp-action="Quanlyhangton" aria-expanded="false">

                                    <span class="hide-menu">Quản lý hàng tồn</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-controller="Main" asp-action="ThongKeMatHangTheoNgay" aria-expanded="false">

                                    <span class="hide-menu">SP đã bán theo ngày</span>
                                </a>
                            </li>



                            <li class="nav-small-cap">
                                <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                                <span class="hide-menu">Thống kê doanh thu</span>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-action="ThongKeTheoNgay" asp-controller="Main" aria-expanded="false">

                                    <span class="hide-menu">Doanh thu theo ngày</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-action="ThongKeKhachHang" asp-controller="Main" aria-expanded="false">

                                    <span class="hide-menu">Doanh thu theo khách hàng</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-action="ThongKeTheoMatHang" asp-controller="Main" aria-expanded="false">

                                    <span class="hide-menu">Doanh thu theo mặt hàng</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-action="Tongdoanhthu" asp-controller="Main" aria-expanded="false">

                                    <span class="hide-menu">Tổng doanh thu</span>
                                </a>
                            </li>
                        }
                        else
                        {

                            @if (ViewBag.nhanvien.Quyen == 0)
                            {
                                <li class="nav-small-cap">
                                    <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                                    <span class="hide-menu">Quản lý hóa đơn</span>
                                </li>
                                <li class="sidebar-item">
                                    <a class="sidebar-link" asp-controller="Main" asp-action="HoaDonChuaDuyet" aria-expanded="false">

                                        <span class="hide-menu">Hóa đơn chưa duyệt</span>
                                    </a>
                                </li>
                                <li class="sidebar-item">
                                    <a class="sidebar-link" asp-controller="Main" asp-action="HoaDonDaDuyet" aria-expanded="false">

                                        <span class="hide-menu">Hóa đơn đã duyệt</span>
                                    </a>
                                </li>
                                <li class="sidebar-item">
                                    <a class="sidebar-link" asp-controller="Main" asp-action="HoaDonDaHuy" aria-expanded="false">

                                        <span class="hide-menu">Hóa đơn đã hủy</span>
                                    </a>
                                </li>
                                <li class="sidebar-item">
                                    <a class="sidebar-link" asp-controller="Main" asp-action="HoaDonDagiao" aria-expanded="false">

                                        <span class="hide-menu">Hóa đơn đã giao</span>
                                    </a>
                                </li>
                                <li class="sidebar-item">
                                    <a class="sidebar-link" asp-controller="Main" asp-action="HangHoanTra" aria-expanded="false">

                                        <span class="hide-menu">Đơn hàng đã hoàn trả</span>
                                    </a>
                                </li>
                            }
                            else
                            {
                                <li class="sidebar-item">
                                    <a class="sidebar-link" asp-controller="Main" asp-action="HoaDonCanGiao" aria-expanded="false">

                                        <span class="hide-menu">Hóa đơn cần giao</span>
                                    </a>
                                </li>
                                <li class="sidebar-item">
                                    <a class="sidebar-link" asp-controller="Main" asp-action="HoaDonDaHuy" aria-expanded="false">

                                        <span class="hide-menu">Hóa đơn đã hủy</span>
                                    </a>
                                </li>
                                <li class="sidebar-item">
                                    <a class="sidebar-link" asp-controller="Main" asp-action="HoaDonDagiao" aria-expanded="false">

                                        <span class="hide-menu">Hóa đơn đã giao</span>
                                    </a>
                                </li>
                                <li class="sidebar-item">
                                    <a class="sidebar-link" asp-controller="Main" asp-action="HangHoanTra" aria-expanded="false">

                                        <span class="hide-menu">Đơn hàng đã hoàn trả</span>
                                    </a>
                                </li>
                            }
                        }



                        <li class="sidebar-item">
                            <a class="sidebar-link" asp-action="Logout" asp-controller="Home">
                                <i class="align-middle" data-feather="check-square"></i> <span class="align-middle">ĐĂNG XUẤT</span>
                            </a>
                        </li>
                    </ul>
                </nav>

            </div>

        </aside>
        <div class="body-wrapper">
            <header class="app-header">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <ul class="navbar-nav">
                        <li class="nav-item d-block d-xl-none">
                            <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                                <i class="ti ti-menu-2"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                                <i class="ti ti-bell-ringing"></i>
                                <div class="notification bg-primary rounded-circle"></div>
                            </a>
                        </li>
                    </ul>
                    <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
                        <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
                            <li class="nav-item dropdown">
                                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                                   aria-expanded="false">
                                    <img src="../assets/images/profile/user-1.jpg" alt="" width="35" height="35" class="rounded-circle">
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                                    <div class="message-body">
                                    <!--   <a class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-user fs-6"></i>
                                            <p class="mb-0 fs-3">Trang chủ</p>
                                        </a>
                                        <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-mail fs-6"></i>
                                            <p class="mb-0 fs-3">My Account</p>
                                        </a>
                                        <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                            <i class="ti ti-list-check fs-6"></i>
                                            <p class="mb-0 fs-3">My Task</p>
                                        </a> --> 
                                        <a asp-action="Logout" asp-controller="Home" class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <div class="container-fluid">
                <div>
                    @RenderBody()
                </div>

            </div>
        </div>
    </div>
    <script src="/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/js/sidebarmenu.js"></script>
    <script src="/assets/js/app.min.js"></script>
    <script src="/assets/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="/assets/libs/simplebar/dist/simplebar.js"></script>
    <script src="/assets/js/dashboard.js"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>

BanTV/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>AdminLTE 2 | Invoice</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="../../bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="../../dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body onload="window.print();">
    <div>
        @RenderBody()
    </div>
    <div class="clearfix"></div>
</body>
</html>