BanTV/Models/MatHang.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace BanTV.Models
{
    public partial class MatHang
    {
        public MatHang()
        {
            CthoaDon = new HashSet<CthoaDon>();
        }

        [Key]
        [Column("mamh")]
        public int Mamh { get; set; }
        [Required]
        [Column("ten")]
        [StringLength(100)]
        public string Ten { get; set; }
        [Column("giagoc")]
        public int Giagoc { get; set; }
        [Column("giaban")]
        public int Giaban { get; set; }
        [Column("soluong")]
        public int Soluong { get; set; }
        [Column("mota")]
        [StringLength(500)]
        public string Mota { get; set; }
        [Column("hinhanh")]
        [StringLength(255)]
        public string Hinhanh { get; set; }
        [Column("daxoa")]
        public int Daxoa { get; set; }
        [Column("madm")]
        public int Madm { get; set; }
        public int? luotxem { get; set; }
        public int luotmua { get; set; }
        public int? hot { get; set; }

        [ForeignKey(nameof(Madm))]
        [InverseProperty(nameof(DanhMuc.MatHang))]
        public virtual DanhMuc MadmNavigation { get; set; }
        [InverseProperty("MamhNavigation")]
        public virtual ICollection<CthoaDon> CthoaDon { get; set; }
    }
}

BanTV/Controllers/MatHangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using Microsoft.AspNetCore.Http;
using System.IO;
using BanTV.Data;
using BanTV.Models;
using System.Data;
using ClosedXML.Excel;

namespace BanTV.Controllers
{
    public class MatHangsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MatHangsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public void GetInfo()
        {
            string email = HttpContext.Session.GetString("nhanvien");
            ViewBag.nhanvien = _context.NhanVien.FirstOrDefault(n => n.Email == email);
        }

        // GET: MatHangs
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.MatHang.Include(m => m.MadmNavigation).OrderByDescending(H => H.Mamh);
            GetInfo();
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: MatHangs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var matHang = await _context.MatHang
                .Include(m => m.MadmNavigation)
                .FirstOrDefaultAsync(m => m.Mamh == id);
            if (matHang == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(matHang);
        }

        // GET: MatHangs/Create
        public IActionResult Create()
        {
            ViewData["Madm"] = new SelectList(_context.DanhMuc, "Madm", "Ten");
            GetInfo();
            return View();
        }

        // POST: MatHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Mamh,Ten,Giagoc,Giaban,Soluong,Mota,Hinhanh,Madm,hot")] MatHang matHang, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                //upload ảnh
                matHang.Hinhanh = Upload(file);
                matHang.Daxoa = 0;
                
                _context.Add(matHang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Madm"] = new SelectList(_context.DanhMuc, "Madm", "Ten", matHang.Madm);
            GetInfo();
            return View(matHang);
        }

        // GET: MatHangs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var matHang = await _context.MatHang.FindAsync(id);
            if (matHang == null)
            {
                return NotFound();
            }
            ViewData["Madm"] = new SelectList(_context.DanhMuc, "Madm", "Ten", matHang.Madm);
            GetInfo();
            return View(matHang);
        }

        // POST: MatHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int mamh,int daxoa, string ten, int giaban, int giagoc, int soluong,string mota, string hinhanh,int luotxem,int luotmua,int madm,int hot, IFormFile file)
        {
            MatHang nv = _context.MatHang.FirstOrDefault(n => n.Mamh == mamh);
            if (nv != null)
            {
                nv.Mamh = mamh;
                nv.Ten = ten;
                nv.Giagoc = giagoc;
                nv.Giaban = giaban;
                nv.Soluong = soluong;
                nv.Mota = mota;
                nv.Madm = madm;
                nv.luotxem = luotxem;
                nv.luotmua = luotmua;
                nv.Daxoa = daxoa;
                nv.hot = hot;
                if (file != null)
                {
                    nv.Hinhanh = hinhanh;
                        hinhanh =Upload(file);
                }
                _context.Update(nv);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            return RedirectToAction(nameof(Edit));
        }

        // GET: MatHangs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var matHang = await _context.MatHang
                .Include(m => m.MadmNavigation)
                .FirstOrDefaultAsync(m => m.Mamh == id);
            if (matHang == null)
            {
                return NotFound();
            }
            GetInfo();
            return View(matHang);
        }

        // POST: MatHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var matHang = await _context.MatHang.FindAsync(id);
            matHang.Daxoa = 1;
            _context.MatHang.Update(matHang);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MatHangExists(int id)
        {
            return _context.MatHang.Any(e => e.Mamh == id);
        }
        public string Upload(IFormFile file)
        {
            string uploadFileName = null;
            if (file != null)
            {
                // phát sinh tên file mới: chuỗi ngẫu nhiên_tên ảnh
                uploadFileName = Guid.NewGuid().ToString() + "_" + file.FileName;
                // chép file về thư mục lưu trữ ảnh
                var path = $"wwwroot\\images\\images\\{uploadFileName}";
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

            }
            return uploadFileName; // trả về tên file
        }
        public async Task<IActionResult> Search(string SearchKey)
        {
            var lstHang = await _context.MatHang.Include(m => m.MadmNavigation)
                            .Where(k => k.Ten.Contains(SearchKey) && k.Daxoa == 0).ToListAsync();
            GetInfo();
            return View(lstHang);
        }


        [HttpGet]
        public async Task<FileResult> ex()
        {
            var mathang = await _context.MatHang.ToListAsync();
            var fil = "mathang.xlsx";
            return Excel(fil, mathang);
        }

        private FileResult Excel(string fil, IEnumerable<MatHang> mathang)
        {
            DataTable data = new DataTable("mathang");
            data.Columns.AddRange(new DataColumn[]
            {
              new DataColumn("Mã mặt hàng"),
              new DataColumn("Tên măth hàng"),
              new DataColumn("Giá gốc"),
              new DataColumn("Giá Bán"),
              new DataColumn("Số lượng"),
              new DataColumn("Mô tả"),
              new DataColumn("Lượt mua"),
              new DataColumn("Lượt xem")
            });

            foreach (var p in mathang)
            {
                data.Rows.Add(p.Mamh, p.Ten, p.Giagoc, p.Giaban, p.Soluong, p.Mota,p.luotmua,p.luotxem);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(data);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fil);
                }
            }
        }

       

    }
}

BanTV/Views/MatHangs/Create.cshtml
@model BanTV.Models.MatHang

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h1>Quản lý mặt hàng</h1>

<h4>MatHang</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Giagoc" class="control-label"></label>
                <input asp-for="Giagoc" class="form-control" />
                <span asp-validation-for="Giagoc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Giaban" class="control-label"></label>
                <input asp-for="Giaban" class="form-control" />
                <span asp-validation-for="Giaban" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Soluong" class="control-label"></label>
                <input asp-for="Soluong" class="form-control" />
                <span asp-validation-for="Soluong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mota" class="control-label"></label>
                <input asp-for="Mota" class="form-control" />
                <span asp-validation-for="Mota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hinhanh" class="control-label"></label>
                <input type="file" name="file" class="form-control" />
                <span asp-validation-for="Hinhanh" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Madm" class="control-label"></label>
                <select asp-for="Madm" class="form-control" asp-items="ViewBag.Madm"></select>
            </div>
            <div class="form-group">
                <label asp-for="hot" class="control-label"></label><br />
                <input type="radio" name="hot" value="0"> không HOT
                <input type="radio" name="hot" value="1"> HOT
            </div>
            </br>
            <div class="form-group">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Trở về</a>
</div>

BanTV/Views/MatHangs/Delete.cshtml
@model BanTV.Models.MatHang

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MatHang</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Giagoc)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Giagoc)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Giaban)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Giaban)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Soluong)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Soluong)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Mota)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Mota)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hinhanh)
        </dt>
        <dd class="col-sm-10">
            <img width="500" src="~/images/images/@Html.DisplayFor(model => model.Hinhanh)" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Daxoa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Daxoa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MadmNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MadmNavigation.Ten)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.hot)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.hot)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Mamh" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BanTV/Views/MatHangs/Details.cshtml
@model BanTV.Models.MatHang

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Details</h1>

<div>
    <h4>MatHang</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Giagoc)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Giagoc)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Giaban)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Giaban)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Soluong)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Soluong)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Mota)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Mota)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Hinhanh)
        </dt>
        <dd class="col-sm-10">
            <img width="500" src="~/images/images/@Html.DisplayFor(model => model.Hinhanh)" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Daxoa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Daxoa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MadmNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MadmNavigation.Ten)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.hot)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.hot)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Mamh">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BanTV/Views/MatHangs/Edit.cshtml
@model BanTV.Models.MatHang

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1>Edit</h1>

<h4>MatHang</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Mamh" />
            <input type="hidden" asp-for="Daxoa" />
            <input type="hidden" asp-for="luotxem" />
            <input type="hidden" asp-for="luotmua" />
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Giagoc" class="control-label"></label>
                <input asp-for="Giagoc" class="form-control" />
                <span asp-validation-for="Giagoc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Giaban" class="control-label"></label>
                <input asp-for="Giaban" class="form-control" />
                <span asp-validation-for="Giaban" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Soluong" class="control-label"></label>
                <input asp-for="Soluong" class="form-control" />
                <span asp-validation-for="Soluong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mota" class="control-label"></label>
                <input asp-for="Mota" class="form-control" />
                <span asp-validation-for="Mota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hinhanh" class="control-label"></label>
                <input type="hidden" asp-for="Hinhanh" class="form-control" />
                <input type="file" name="file" class="form-control" />
                <span asp-validation-for="Hinhanh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Madm" class="control-label"></label>
                <select asp-for="Madm" class="form-control" asp-items="ViewBag.Madm"></select>
                <span asp-validation-for="Madm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">HOT</label><br />
                @if (Model.hot == 1)
                {

                    <input type="radio" id="0" name="hot" value="0"> <label for="0">không HOT</label>
                    <input type="radio" id="1" name="hot" value="1" checked="true"> <label for="1">HOT</label>
                }
                else
                {
                    <input type="radio" id="0" name="hot" value="0" checked="true"> <label for="0">không HOT</label>
                    <input type="radio" id="1" name="hot" value="1"> <label for="1">HOT</label>
                }
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BanTV/Views/MatHangs/Index.cshtml
@model IEnumerable<BanTV.Models.MatHang>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row text-center">
    <div class="d-flex align-items-stretch">
        <div class="card w-100">
            <div class="card-body p-4">
                <h5 class="card-title fw-semibold mb-4">Quản lý mặt hàng</h5>
                <div class="table-responsive">
                    <td class="border-bottom-0">
                        <div class="d-flex align-items-center gap-2">
                            <span class="badge bg-primary rounded-3 fw-semibold "><a class="text-white" asp-action="Create">Thêm mặt hàng</a></span>
                        </div>
                        <br />
                        <div class="d-flex flex-row">
                            <form asp-controller="MatHangs" asp-action="Search">
                                <input type="search" name="SearchKey" placeholder="Tìm kiếm...." class="form-control" />
                            </form>

                        </div>
                        <br />
                        <div class="d-flex align-items-center gap-2">
                            <span class="badge bg-primary rounded-3 fw-semibold "><a class="text-white" asp-action="ex">Xuất Excel</a></span>
                        </div>
                    </td>

                    <table class="table text-nowrap mb-0 align-middle">
                        <thead class="text-dark fs-4">
                            <tr>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0 text-center">Tên mặt hàng</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">giá gốc</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">giá bán</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Hình ảnh</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Mặt hàng đã xóa</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Tên danh mục</h6>
                                </th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Ten)
                                    </td>
                                    <td>
                                        @(item.Giagoc.ToString("n0"))đ
                                    </td>
                                    <td>
                                        @(item.Giaban.ToString("n0"))đ
                                    </td>
                                    <td>
                                        <img src="~/images/images/@Html.DisplayFor(modelItem => item.Hinhanh)" class="img-thumbnail" width="100" />
                                    </td>
                                    @if (item.Daxoa == 0)
                                    {
                                        <td></td>
                                    }
                                    else
                                    {
                                        <td><i class="bi bi-x-circle-fill text-danger"></i></td>
                                    }
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MadmNavigation.Ten)
                                    </td>
                                    <td class="border-bottom-0">
                                        <span class="badge bg-secondary rounded-3 fw-semibold"> <a class="text-white" asp-action="Edit" asp-route-id="@item.Mamh"> Sửa</a></span>
                                        <span class="badge bg-success rounded-3 fw-semibold"> <a class="text-white" asp-action="Details" asp-route-id="@item.Mamh">Xem</a></span>
                                        <span class="badge bg-danger rounded-3 fw-semibold"><a class="text-white" asp-action="Delete" asp-route-id="@item.Mamh">Xóa</a></span>
                                    </td>
                                    <td class="border-bottom-0">
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

BanTV/Views/MatHangs/Search.cshtml
@model IEnumerable<BanTV.Models.MatHang>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row text-center">
    <div class="d-flex align-items-stretch">
        <div class="card w-100">
            <div class="card-body p-4">
                <h5 class="card-title fw-semibold mb-4">Quản lý mặt hàng</h5>
                <div class="table-responsive">
                    <td class="border-bottom-0">
                        <div class="d-flex align-items-center gap-2">
                            <span class="badge bg-primary rounded-3 fw-semibold "><a class="text-white" asp-action="Create">Thêm mặt hàng</a></span>
                        </div>
                        <br />
                        <div class="d-flex flex-row">
                            <form asp-controller="MatHangs" asp-action="Search">
                                <input type="search" name="SearchKey" placeholder="Tìm kiếm...." class="form-control" />
                            </form>

                        </div>
                        <br />
                        <div class="d-flex align-items-center gap-2">
                            <span class="badge bg-primary rounded-3 fw-semibold "><a class="text-white" asp-action="ex">Xuất Excel</a></span>
                        </div>
                    </td>
                    <table class="table text-nowrap mb-0 align-middle">
                        <thead class="text-dark fs-4">
                            <tr>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0 text-center">Tên mặt hàng</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">giá gốc</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">giá bán</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Hình ảnh</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Mặt hàng đã xóa</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Tên danh mục</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Sửa sản phẩm</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Xem sản phẩm</h6>
                                </th>
                                <th class="border-bottom-0">
                                    <h6 class="fw-semibold mb-0">Xóa sản phẩm</h6>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Ten)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Giagoc)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Giaban)
                                    </td>
                                    <td>
                                        <img src="~/images/images/@Html.DisplayFor(modelItem => item.Hinhanh)" class="img-thumbnail" width="100" />
                                    </td>
                                    @if (item.Daxoa == 0)
                                    {
                                        <td></td>
                                    }
                                    else
                                    {
                                        <td><i class="bi bi-x-circle-fill text-danger"></i></td>
                                    }
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MadmNavigation.Ten)
                                    </td>
                                    <td class="border-bottom-0">
                                        <div class="d-flex align-items-center gap-2">
                                            <span class="badge bg-secondary rounded-3 fw-semibold"> <a class="text-white" asp-action="Edit" asp-route-id="@item.Madm"> Sửa</a></span>
                                        </div>
                                    </td>
                                    <td class="border-bottom-0">
                                        <div class="d-flex align-items-center gap-2">
                                            <span class="badge bg-success rounded-3 fw-semibold"> <a class="text-white" asp-action="Details" asp-route-id="@item.Madm">Xem</a></span>
                                        </div>
                                    </td>
                                    <td class="border-bottom-0">
                                        <div class="d-flex align-items-center gap-2">
                                            <span class="badge bg-danger rounded-3 fw-semibold"><a class="text-white" asp-action="Delete" asp-route-id="@item.Madm">Xóa</a></span>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>